version: '3.1'
services:

  redis:
    image: 'redis:6.2'
    networks:
      - hmpps_int
    ports:
      - '6380:6379'

  wiremock:
    image: wiremock/wiremock
    networks:
    - hmpps_int
    container_name: wiremock_test
    restart: always
    command: --local-response-templating
    ports:
      - "9999:8080"

networks:
  hmpps_int:
