name: Build project
description: Specific steps to setup the repo
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.8.0
      with:
        node-version-file: '.nvmrc'

    - uses: actions/setup-node@v3
      with:
        cache: 'npm'

    - name: Installing dependencies
      run: npm install
      shell: bash

    - name: Typechecking the code
      run: npm run typecheck
      shell: bash
