name: Integration Tests

on:
  pull_request:
  merge_group:
  push:
    branches:
      - main

env:
  NODE_ENV: test
  API_CLIENT_ID: approved-premises
  API_CLIENT_SECRET: clientsecret

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - uses: ./.github/shared/setup

      - name: Building source
        run: npm run build

      - name: Starting the backing services in Docker
        run: |
          script/utils/launch-docker.sh
          docker-compose -f docker-compose-test.yml up -d

      - name: Running integration tests
        run: npm run test:integration
