name: Lint

on:
  pull_request:
  merge_group:
  push:
    branches:
      - main

env:
  NODE_ENV: test
  API_CLIENT_ID: approved-premises
  API_CLIENT_SECRET: clientsecret

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - uses: ./.github/shared/setup

      - name: Linting the code
        run: npm run lint

      - name: Checking shell scripts
        run: node_modules/.bin/shellcheck ./script/**/*[^utils] ./script/utils/**
