name: Unit Tests

on:
  pull_request:
  merge_group:
  push:
    branches:
      - main

env:
  NODE_ENV: test
  API_CLIENT_ID: approved-premises
  API_CLIENT_SECRET: clientsecret

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - uses: ./.github/shared/setup

      - name: Running unit tests
        run: npm test
